### ISSUE TITLE
bug: Unable to run npx prisma db seed nor launch the site

### ISSUE THREAD

**Issue by 25zeeshan** [code100x/daily-code#252]
### Issue 1:
npx prisma db seed failing with following error :
```
Running seed command `ts-node prisma/seed.ts` ...
/home/ahsan/Desktop/Open-source/daily-code/packages/db/node_modules/.prisma/client/default.js:43
    throw new Error(
          ^
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report
    at new PrismaClient (/home/ahsan/Desktop/Open-source/daily-code/packages/db/node_modules/.prisma/client/default.js:43:11)
    at prismaClientSingleton (/home/ahsan/Desktop/Open-source/daily-code/packages/db/src/index.ts:4:10)
    at Object.<anonymous> (/home/ahsan/Desktop/Open-source/daily-code/packages/db/src/index.ts:14:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/home/ahsan/Desktop/Open-source/daily-code/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ahsan/Desktop/Open-source/daily-code/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

And when I run npx prisma generate - fails with following error

```
Prisma schema loaded from prisma/schema.prisma
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'add'
Error: Command failed with exit code 1: yarn add @prisma/client@5.12.0
```

**To Reproduce**
1. Fork and clone the repo, then make a new git branch
2. using node version 18.17.0
3. run npm install - then update db url in .env and run npx prisma migrate dev
4. run npx prisma db seed

### Issue 2:

I am expecting `npm run dev` to launch the site even when db seed is not done. However, it fails with following error :

```
> dev
> turbo dev

• Packages in scope: @repo/common, @repo/db, @repo/eslint-config, @repo/store, @repo/typescript-config, @repo/ui, web
• Running dev in 7 packages
• Remote caching disabled
web:dev: cache bypass, force executing fe05e25f6ecbd896
web:dev: 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
web:dev: ERROR: command finished with error: command (/home/ahsan/Desktop/Open-source/daily-code/apps/web) /usr/bin/yarn run dev exited (1)
web#dev: command (/home/ahsan/Desktop/Open-source/daily-code/apps/web) /usr/bin/yarn run dev exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    400ms 
Failed:    web#dev

 ERROR  run failed: command  exited (1)
```

**Comment by SujithThirumalaisamy** [comment]
We are not using npm anywhere. You should be using yarn. And the readme file is well and tested. I should be fine.

**Comment by 25zeeshan** [comment]
Thanks Sujit, it works with Yarn.
