### ISSUE TITLE
bug: Build broken

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#373]
`npm run build` crashing with 

Linting and checking validity of types    
   Collecting page data  ..Error: Invariant: headers() expects to have requestAsyncStorage, none available.
    at u (/Users/harkiratsingh/Projects/daily-code/apps/web/.next/server/chunks/679.js:30:27018)
    at s (/Users/harkiratsingh/Projects/daily-code/apps/web/.next/server/chunks/679.js:30:20321)
    at /Users/harkiratsingh/Projects/daily-code/apps/web/.next/server/chunks/576.js:11:2536
    at t.a (/Users/harkiratsingh/Projects/daily-code/apps/web/.next/server/webpack-runtime.js:1:889)
    at 5554 (/Users/harkiratsingh/Projects/daily-code/apps/web/.next/server/chunks/576.js:11:2299)
    at Function.t (/Users/harkiratsingh/Projects/daily-code/apps/web/.next/server/webpack-runtime.js:1:128)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (/Users/harkiratsingh/Projects/daily-code/node_modules/next/dist/build/utils.js:919:21)
    at async /Users/harkiratsingh/Projects/daily-code/node_modules/next/dist/build/utils.js:1138:17
    at async Span.traceAsyncFn (/Users/harkiratsingh/Projects/daily-code/node_modules/next/dist/trace/trace.js:151:20)

> Build error occurred
Error: Failed to collect page data for /profile

**Comment by dyaipayan22** [comment]
@hkirat Can I take it up?

**Comment by SujithThirumalaisamy** [comment]
> @hkirat Can I take it up?

Already done! #374 
Can be closed. @hkirat
